# Header
menu:
  é¦–é : /
  é—œæ–¼: /about

# ä¸»é¡µbannerå›¾
banner: https://qiniu.sukoshi.xyz/src/images/68686407_p0.jpg

# ç«™ç‚¹é€šçŸ¥ä¿¡æ¯
notice: ç„¡æ–°æ¶ˆæ¯

# ä½œè€…ä¿¡æ¯
author:
  name: FlyFish
  avatar: https://i.pinimg.com/564x/e4/c7/22/e4c722ddd398c0f1a1f0e0ba0b1d8f48.jpg
  description: I have a dream

toc:
  max_depth: 3 # ç”Ÿæˆ TOC çš„æœ€å¤§æ·±åº¦
  min_depth: 2 # ç”Ÿæˆ TOC çš„æœ€å°æ·±åº¦

comments:
  enable: false
  use: 'valine' # valine || disqus
  # valine è¯„è®º
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # è¿™é‡ŒappIdå’ŒappKeyä¸€å®šä¸€å®šè¦æ”¹æˆè‡ªå·±çš„ï¼Œæ²¡æœ‰çš„è¯å»https://leancloud.cnè¿™ä¸ªç½‘ç«™æ³¨å†Œåˆ›å»ºä¸€ä¸ª
  valine:
    appId: 
    appKey: 
    avatar: mm
    placeholder: èªªé»ä»€éº¼
    notify: true
    visitor: true
    pageSize: 10
  # disqus è¯„è®º
  # docs: https://disqus.com/
  disqus:
    website: 
    error: Some error occurred ğŸ˜¢.

# dplayer è§†é¢‘æ’­æ”¾
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer éŸ³é¢‘æ’­æ”¾
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# mathjax LaTeXå…¬å¼æ”¯æŒ
#docs: http://docs.mathjax.org/en/latest/
mathjax:
    enable: true

# è°·æ­Œåˆ†æ
google_analytics: 
# gaugesåˆ†æ
gauges_analytics: 
# ç«™ç‚¹ico
favicon: /favicon.png


# Social Icon
social_icon:
  enable: true
  icons:
    ins     :
    github  : https://github.com/a45s67/
    twitter : https://twitter.com/b45s67
